const VACCINES = {
  COVID19: "COVID-19",
  DTaP_IPV: "Diphtheria, Tetanus, Whooping Cough & Polio",
  DTaP_IPV_Hib: "Diphtheria, Tetanus, Whooping Cough, Polio & Hib",
  FLU: "Flu",
  HA: "Hepatitis A",
  HAHB: "Hepatitis A & B",
  HB: "Hepatitis B",
  HPV: "HPV (Human Papillomavirus)",
  Hib: "Hib",
  IPV: "Polio",
  MMR: "Measles, Mumps & Rubella (MMR)",
  MMRV: "Measles, Mumps, Rubella & Chickenpox (MMRV)",
  MPOX: "Mpox",
  MenB: "Meningitis B",
  MenC_ACYW: "Meningitis ACYW",
  PNEU_C15: "Pneumococcal (C15)",
  PNEU_C20: "Pneumococcal (C20)",
  PNEU_P23: "Pneumococcal (P23)",
  RABIES: "Rabies",
  ROTA: "Rotavirus",
  RSV_ADULT: "RSV (Adult)",
  RSV_NIRSEVIMAB: "RSV (Baby Protection - Nirsevimab)",
  TD: "Tetanus & Diphtheria (Td)",
  TDAP: "Tetanus, Diphtheria & Whooping Cough (Tdap)",
  TDAP_IPV: "Tetanus, Diphtheria, Whooping Cough & Polio (Tdap-IPV)",
  VAR: "Chickenpox (Varicella)",
};