const VACCINES = {
  COVID19: "COVID-19",
  DTaP_IPV: "Diphtheria, Tetanus, Whooping Cough & Polio",
  DTaP_IPV_Hib: "Diphtheria, Tetanus, Whooping Cough, Polio & Hib",
  FLU: "Flu",
  HA: "Hepatitis A",
  HAHB: "Hepatitis A & B",
  HB: "Hepatitis B",
  HPV: "HPV (Human Papillomavirus)",
  Hib: "Hib (Influenza type b)",
  IPV: "Polio",
  MMR: "Measles, Mumps & Rubella (MMR)",
  MMRV: "Measles, Mumps, Rubella & Chickenpox (MMRV)",
  MPOX: "Mpox",
  MenB: "Meningitis B",
  MenC_ACYW: "Meningitis ACYW",
  PNEU_C15: "Pneumococcal",
  PNEU_C20: "Pneumococcal",
  PNEU_P23: "Pneumococcal",
  RABIES: "Rabies",
  ROTA: "Rotavirus",
  RSV_ADULT: "RSV",
  RSV_NIRSEVIMAB: "RSV",
  TD: "Tetanus & Diphtheria (Td)",
  TDAP: "Tetanus, Diphtheria & Whooping Cough (Tdap)",
  TDAP_IPV: "Tetanus, Diphtheria, Whooping Cough & Polio (Tdap-IPV)",
  VAR: "Chickenpox (Varicella)",
};

const RISK_TAGS = {
  ASPLENIA: "No spleen (asplenia)",
  CANCER: "Cancer",
  CAR_T_THERAPY: "CAR-T therapy",
  CHRONIC_HEART_DISEASE: "Chronic heart disease",
  CHRONIC_KIDNEY_DISEASE: "Chronic kidney disease",
  CHRONIC_LIVER_DISEASE: "Chronic liver disease",
  CHRONIC_LUNG_DISEASE: "Chronic lung disease",
  COCHLEAR_IMPLANT: "Cochlear implant",
  COMPLEMENT_DEFICIENCY: "Complement deficiency",
  COVID_ELIGIBLE_NOW: "COVID-19 vaccine not administered",
  CSF_LEAK: "CSF leak (cerebrospinal fluid leak)",
  DIABETES: "Diabetes",
  HAHB_ELIGIBLE: "Hepatitis A & B vaccine not administered",
  HAV_CLOSE_CONTACT: "Close contact exposure to Hepatitis A",
  HAV_COMMON_EXPOSURE: "Common exposure to Hepatitis A",
  HBV_HIGH_RISK: "High risk for Hepatitis B",
  HEMODIALYSIS: "Hemodialysis",
  HEPATITIS_C: "Hepatitis C",
  HIGH_GRADE_CERVICAL_DYSPLASIA: "High-grade cervical dysplasia",
  HIV: "HIV",
  HYPO_SPLENIA: "Reduced spleen function (hyposplenia)",
  IMMUNOCOMPROMISED: "Immunocompromised",
  IMMUNOSUPPRESSIVE_THERAPY: "On immunosuppressive therapy",
  INFLUENZA_SEASON_ACTIVE: "Flu season is active",
  MEASLES_OUTBREAK: "Measles",
  MENB_HIGH_RISK: "High risk for Meningitis B",
  MENINGO_HIGH_RISK: "High risk for meningococcal disease",
  MPOX_POST_EXPOSURE_CLOSE_CONTACT: "Mpox",
  NEPHROTIC_SYNDROME: "Nephrotic syndrome",
  OCCUPATIONAL_BLOOD_EXPOSURE: "Work-related blood exposure",
  PNEUMOCOCCAL_HIGH_RISK: "High risk for pneumococcal disease",
  POLIO_CATCHUP_NEEDS_BOOSTER: "Polio vaccine not administered",
  PREGNANT: "Pregnant",
  RABIES_EXPOSURE: "Rabies exposure",
  RECURRENT_RESP_PAPILLOMATOSIS: "Recurrent respiratory papillomatosis",
  RESIDES_IN_PCH: "Lives in a personal care home",
  RSV_HIGH_RISK_ADULT: "High risk for RSV (adult)",
  RSV_HIGH_RISK_INFANT_PROGRAM_APPROVED: "High risk infant approved for RSV program",
  SOLID_ORGAN_TRANSPLANT: "Solid organ transplant",
  STEM_CELL_TRANSPLANT: "Stem cell transplant",
  TRANSPLANT: "Transplant recipient",
  VARICELLA_IMMUNE: "Immune to chickenpox (varicella)",
  VETERINARIAN: "Veterinarian",
  WILDLIFE_WORKER: "Wildlife worker"
};

export {VACCINES, RISK_TAGS};