const VACCINES = {
  COVID19: "COVID-19",
  DTaP_IPV: "Diphtheria, Tetanus, Whooping Cough & Polio",
  DTaP_IPV_Hib: "Diphtheria, Tetanus, Whooping Cough, Polio & Hib",
  FLU: "Flu",
  HA: "Hepatitis A",
  HAHB: "Hepatitis A & B",
  HB: "Hepatitis B",
  HPV: "HPV (Human Papillomavirus)",
  Hib: "Hib",
  IPV: "Polio",
  MMR: "Measles, Mumps & Rubella (MMR)",
  MMRV: "Measles, Mumps, Rubella & Chickenpox (MMRV)",
  MPOX: "Mpox",
  MenB: "Meningitis B",
  MenC_ACYW: "Meningitis ACYW",
  PNEU_C15: "Pneumococcal (C15)",
  PNEU_C20: "Pneumococcal (C20)",
  PNEU_P23: "Pneumococcal (P23)",
  RABIES: "Rabies",
  ROTA: "Rotavirus",
  RSV_ADULT: "RSV (Adult)",
  RSV_NIRSEVIMAB: "RSV (Baby Protection - Nirsevimab)",
  TD: "Tetanus & Diphtheria (Td)",
  TDAP: "Tetanus, Diphtheria & Whooping Cough (Tdap)",
  TDAP_IPV: "Tetanus, Diphtheria, Whooping Cough & Polio (Tdap-IPV)",
  VAR: "Chickenpox (Varicella)",
};

const RISK_TAGS = {
  ALCOHOL_USE_DISORDER: "Alcohol use disorder",
  ANIMAL_CONTROL_WORKER: "Animal control worker",
  ASPLENIA: "No spleen (asplenia)",
  CANCER: "Cancer",
  CAR_T_THERAPY: "CAR-T therapy",
  CCMB_SCHEDULE: "CancerCare Manitoba schedule",
  CHRONIC_HEART_DISEASE: "Chronic heart disease",
  CHRONIC_KIDNEY_DISEASE: "Chronic kidney disease",
  CHRONIC_LIVER_DISEASE: "Chronic liver disease",
  CHRONIC_LUNG_DISEASE: "Chronic lung disease",
  COCHLEAR_IMPLANT: "Cochlear implant",
  COMPLEMENT_DEFICIENCY: "Complement deficiency",
  COVID_ELIGIBLE_NOW: "Eligible now for COVID-19 vaccine",
  CSF_LEAK: "CSF leak (cerebrospinal fluid leak)",
  DIABETES: "Diabetes",
  GBMSM: "Gay, bisexual, and other men who have sex with men (GBMSM)",
  GRADE6_PROGRAM: "Grade 6 school program",
  HAHB_ELIGIBLE: "Eligible for Hepatitis A & B vaccine",
  HAV_CLOSE_CONTACT: "Close contact exposure to Hepatitis A",
  HAV_COMMON_EXPOSURE: "Common exposure to Hepatitis A",
  HAV_OUTBREAK_ISLAND_LAKE: "Hepatitis A outbreak - Island Lake",
  HAV_OUTBREAK_PEGUIS: "Hepatitis A outbreak - Peguis",
  HAV_TRAVEL_WORK_ISLAND_LAKE: "Travel/work in Island Lake (Hepatitis A risk)",
  HAV_TRAVEL_WORK_PEGUIS: "Travel/work in Peguis (Hepatitis A risk)",
  HBV_CATCHUP_MISSED_SCHOOL: "Missed school Hepatitis B vaccine (catch-up)",
  HBV_HIGH_RISK: "High risk for Hepatitis B",
  HBV_SCHOOL_PROGRAM: "Hepatitis B school program",
  HEALTHCARE_WORKER: "Healthcare worker",
  HEMODIALYSIS: "Hemodialysis",
  HEPATITIS_C: "Hepatitis C",
  HIGH_GRADE_CERVICAL_DYSPLASIA: "High-grade cervical dysplasia",
  HIV: "HIV",
  HOMECARE_CLIENT: "Home care client",
  HOUSEHOLD_CONTACT_HBV: "Household contact of someone with Hepatitis B",
  HPV_CATCHUP_SCHOOL: "Missed school HPV vaccine (catch-up)",
  HPV_SCHOOL_PROGRAM: "HPV school program",
  HYPO_SPLENIA: "Reduced spleen function (hyposplenia)",
  IMMUNOCOMPROMISED: "Immunocompromised",
  IMMUNOSUPPRESSIVE_THERAPY: "On immunosuppressive therapy",
  INCARCERATED_MALE_UNDER18: "Incarcerated male under 18",
  INFLUENZA_SEASON_ACTIVE: "Flu season is active",
  INJECTION_DRUG_USE: "Injection drug use",
  LIVES_IN_FIRST_NATIONS_COMMUNITY: "Lives in a First Nations community",
  MEASLES_OUTBREAK: "Measles outbreak exposure/risk",
  MEASLES_TRAVEL: "Measles travel risk",
  MENB_HIGH_RISK: "High risk for Meningitis B",
  MENB_OUTBREAK_CONTROL: "Meningitis B outbreak control",
  MENC_CATCHUP_MISSED_GRADE4: "Missed Grade 4 meningitis vaccine (catch-up)",
  MENC_MISSED_12M: "Missed meningitis vaccine at 12 months",
  MENC_SCHOOL_PROGRAM: "Meningitis school program",
  MENINGO_HIGH_RISK: "High risk for meningococcal disease",
  MENINGO_OUTBREAK_INDIGENOUS_COMMUNITY: "Meningococcal outbreak risk in Indigenous community",
  MPOX_POST_EXPOSURE_CLOSE_CONTACT: "Close contact exposure to mpox",
  MPOX_PREP_GBMSM_HIGH_RISK: "Mpox prevention - GBMSM at high risk",
  MPOX_PREP_HEALTHCARE_OUTBREAK_SUPPORT: "Mpox prevention - healthcare outbreak support worker",
  MPOX_PREP_LAB_PERSONNEL: "Mpox prevention - lab personnel",
  MPOX_PREP_SEX_VENUE_STAFF: "Mpox prevention - sex venue staff",
  MPOX_PREP_SEX_WORKER: "Mpox prevention - sex worker",
  MPOX_PREP_TRAVEL_CLADE_I_AREA: "Mpox prevention - travel to clade I risk area",
  NEPHROTIC_SYNDROME: "Nephrotic syndrome",
  OCCUPATIONAL_BLOOD_EXPOSURE: "Work-related blood exposure",
  PCH_RESPITE_CLIENT: "Personal care home respite client",
  PNEUMOCOCCAL_HIGH_RISK: "High risk for pneumococcal disease",
  POLIO_CATCHUP_NEEDS_BOOSTER: "Polio catch-up booster needed",
  POST_SECONDARY_STUDENT: "Post-secondary student",
  PREGNANT: "Pregnant",
  RABIES_EXPOSURE: "Rabies exposure",
  RABIES_LAB_PERSONNEL: "Rabies lab personnel",
  RABIES_OCCUPATIONAL_RISK: "Work-related rabies risk",
  RECURRENT_RESP_PAPILLOMATOSIS: "Recurrent respiratory papillomatosis",
  RESIDES_IN_PCH: "Lives in a personal care home",
  RSV_HIGH_RISK_ADULT: "High risk for RSV (adult)",
  RSV_HIGH_RISK_INFANT_PROGRAM_APPROVED: "High risk infant approved for RSV program",
  SEXUAL_ASSAULT_SURVIVOR: "Sexual assault survivor",
  SEXUAL_CONTACT_HBV: "Sexual contact of someone with Hepatitis B",
  SOLID_ORGAN_TRANSPLANT: "Solid organ transplant",
  STEM_CELL_TRANSPLANT: "Stem cell transplant",
  TRANSGENDER: "Transgender",
  TRANSPLANT: "Transplant recipient",
  VARICELLA_IMMUNE: "Immune to chickenpox (varicella)",
  VARICELLA_SPECIALIST_APPROVED: "Chickenpox vaccine approved by specialist",
  VETERINARIAN: "Veterinarian",
  WILDLIFE_WORKER: "Wildlife worker"
};